import { useState } from "react";
import { pdf, Document, Page, Text, View, StyleSheet, Font } from "@react-pdf/renderer";
import { pToRupee, sumMustHavePaise } from "@kothi/shared/types/budget";
import type { BudgetState } from "@kothi/shared/types/budget";
import { useTranslation } from "react-i18next";

// Noto Sans Devanagari supports Marathi characters
Font.register({
  family: "NotoSans",
  src: "/fonts/NotoSansDevanagari-Regular.ttf",
});

const styles = StyleSheet.create({
  page: { padding: 32, fontFamily: "NotoSans", fontSize: 11 },
  heading: { fontSize: 18, fontWeight: "bold", marginBottom: 4 },
  subheading: { fontSize: 12, color: "#666", marginBottom: 20 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 12, fontWeight: "bold", marginBottom: 8, color: "#333" },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 5, borderBottomWidth: 0.5, borderBottomColor: "#eee" },
  label: { flex: 1, color: "#444" },
  value: { fontWeight: "bold", color: "#222" },
  badge: { fontSize: 9, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 10, marginRight: 6 },
  mustBadge: { backgroundColor: "#edf5e5", color: "#5c7a3e" },
  waitBadge: { backgroundColor: "#f3f3f3", color: "#888" },
  footer: { position: "absolute", bottom: 24, left: 32, right: 32, fontSize: 9, color: "#aaa", textAlign: "center" },
});

interface Props {
  state: BudgetState;
}

export default function BudgetPdfDocument({ state }: Props) {
  const { t } = useTranslation();
  const [generating, setGenerating] = useState(false);

  const mustPaise = sumMustHavePaise(state.priorityCategories);

  const handleDownload = async () => {
    setGenerating(true);
    try {
      const doc = (
        <Document>
          <Page size="A4" style={styles.page}>
            <Text style={styles.heading}>Koyta-Sathi — Budget Plan 2026</Text>
            <Text style={styles.subheading}>Generated by Koyta-Sathi · SOPPECOM × Harvard Research</Text>

            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Advance Plan</Text>
              <View style={styles.row}>
                <Text style={styles.label}>Planned Advance</Text>
                <Text style={styles.value}>₹{pToRupee(state.planning?.plannedAdvancePaise ?? 0)}</Text>
              </View>
              <View style={styles.row}>
                <Text style={styles.label}>Priority (Must-Have) Amount</Text>
                <Text style={styles.value}>₹{pToRupee(mustPaise)}</Text>
              </View>
            </View>

            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Priority Categories</Text>
              {state.priorityCategories.map((cat, i) => (
                <View key={i} style={styles.row}>
                  <View style={{ flexDirection: "row", alignItems: "center", flex: 1 }}>
                    <Text style={[styles.badge, cat.classification === "must" ? styles.mustBadge : styles.waitBadge]}>
                      {cat.classification === "must" ? "MUST" : "WAIT"}
                    </Text>
                    <Text style={styles.label}>{cat.label}</Text>
                  </View>
                  <Text style={styles.value}>{cat.amountPaise > 0 ? `₹${pToRupee(cat.amountPaise)}` : "—"}</Text>
                </View>
              ))}
            </View>

            <Text style={styles.footer}>
              Koyta-Sathi · SOPPECOM × Harvard Research · Data will be deleted by April 2027
            </Text>
          </Page>
        </Document>
      );

      const blob = await pdf(doc).toBlob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "koyta-sathi-budget-2026.pdf";
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <button
      className="btn btn-primary btn-full"
      style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 8 }}
      disabled={generating}
      onClick={handleDownload}
    >
      {generating ? (
        <span className="spinner" style={{ width: 16, height: 16 }} />
      ) : (
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
          <polyline points="7 10 12 15 17 10" />
          <line x1="12" y1="15" x2="12" y2="3" />
        </svg>
      )}
      {generating ? "Generating…" : t("budget.pdf.download")}
    </button>
  );
}
